Bruces_ratings = {
    "Liar's Poker": 4.0,
    "The Big Short: Inside the Doomsday Machine": 5.0,
    "Flash Boys: A Wall Street Revolt": 5.0,
    "The Undoing Project: A Friendship That Changed Our Minds": 4.0,
    "Alexander Hamilton":5.0,
    "The House of Morgan: An American Banking Dynasty and the Rise of Modern Finance": 5.0,
    "The Hobbit, or There and Back Again": 3.0,
    "A Storm of Swords (A Song of Ice and Fire, #3)": 5.0,
    "Advanced Programming in the UNIX Environment": 4.0,
    "The Elements of Statistical Learning: Data Mining, Inference, and Prediction": 4.0,
    "The Brief Wondrous Life of Oscar Wao": 5.0,
    "Sapiens: A Brief History of Humankind": 5.0,
    "The Emperor of All Maladies: A Biography of Cancer": 5.0,
    "Vagabonding: An Uncommon Guide to the Art of Long-Term World Travel": 4.0,
    "The Shock Doctrine: The Rise of Disaster Capitalism": 5.0,
    "Cryptonomicon": 5.0,
    "No Ordinary Time: Franklin and Eleanor Roosevelt: The Home Front in World War II": 5.0,
    "Tools of Titans: The Tactics, Routines, and Habits of Billionaires, Icons, and World-Class Performers": 3.0,
    "The Search For Modern China": 5.0,
    "The Art of Learning: A Journey in the Pursuit of Excellence": 5.0,
    "The Three-Body Problem (Remembrance of Earth’s Past #1)": 5.0,
    "Team of Rivals: The Political Genius of Abraham Lincoln": 5.0,
    "Genghis Khan and the Making of the Modern World": 4.0,
}
